apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: once-pvc
  namespace: llm-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: weights
