apiVersion: v1
kind: Service
metadata:
  name: longago-service
  namespace: llm-ns
spec:
  selector:
    app: longago
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: ClusterIP
