apiVersion: v1
kind: Service
metadata:
  name: onceupon-service
  namespace: llm-ns
spec:
  selector:
    app: onceupon
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: ClusterIP
